# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Ensure only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload static files to artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload only the `src` folder containing `index.html`
          path: 'src'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send email notification on successful deployment
        if: ${{ success() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: "Deployment Successful - GitHub Pages"
          body: |
            Hello,

            I'm writing to let you know that my static website has been deployed successfully to GitHub Pages.

            Your website is now live at:
            ${{ steps.deployment.outputs.page_url }}

            Thanks for your attention.

            Best regards,
            Peng Seang Sim
            [Visit my site](https://pengseangsim.com)
          to: pengseangsim210@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          secure: true
